### ISSUE TITLE
ember-power-select is causing error after upgrading from 1.5.7 to 2.0.1

### ISSUE THREAD

**Issue by yads** [gpoitch/ember-cli-less#67]
We're using the [ember-power-select](https://github.com/cibernox/ember-power-select) plugin and after upgrading to ember-cli-less 2.0.1 we're getting the following LessCompiler error:

>SyntaxError: Cannot read property 'eval' of null in /var/folders/kb/cy0txbmx1g579kycjsyfl5q89dlr3b/T/broccoli-674726wFPAksadaZw/out-335-broccoli_merge_trees_full_application/app/styles/ember-power-select/variables.less on line 19, column 1:
18 @ember-power-select-border-color: #aaaaaa;
19 @ember-power-select-focus-border-color: @ember-power-select-border-color;
20 @ember-power-select-default-border: 1px solid @ember-power-select-border-color;
>
>Syntax (LessCompiler)
>
>Cannot read property 'eval' of null
>
>
>Stack Trace and Error Report: /var/folders/kb/cy0txbmx1g579kycjsyfl5q89dlr3b/T/error.dump.f49937ceb098cb440848bb3d55b7d998.log

here's the error snippet from the error dump referenced above

> ERROR Summary:
> 
>   - broccoliBuilderErrorStack: TypeError: Cannot read property 'eval' of null
>     at Array.<anonymous> (/Users/vkazakov/dev/Mothership/frontend/node_modules/less/lib/less/tree/variable.js:39:31)
>     at Node.Variable.find (/Users/vkazakov/dev/Mothership/frontend/node_modules/less/lib/less/tree/variable.js:55:17)
>     at Node.Variable.eval (/Users/vkazakov/dev/Mothership/frontend/node_modules/less/lib/less/tree/variable.js:27:21)
>     at Node.Expression.eval (/Users/vkazakov/dev/Mothership/frontend/node_modules/less/lib/less/tree/expression.js:39:37)
>     at Node.Value.eval (/Users/vkazakov/dev/Mothership/frontend/node_modules/less/lib/less/tree/value.js:23:30)
>     at Node.Declaration.eval (/Users/vkazakov/dev/Mothership/frontend/node_modules/less/lib/less/tree/declaration.js:62:33)
>     at Node.Ruleset.eval (/Users/vkazakov/dev/Mothership/frontend/node_modules/less/lib/less/tree/ruleset.js:181:50)
>     at module.exports (/Users/vkazakov/dev/Mothership/frontend/node_modules/less/lib/less/transform-tree.js:76:22)
>     at ParseTree.toCSS (/Users/vkazakov/dev/Mothership/frontend/node_modules/less/lib/less/parse-tree.js:14:25)
>     at /Users/vkazakov/dev/Mothership/frontend/node_modules/less/lib/less/render.js:35:40
>   - codeFrame: Cannot read property 'eval' of null
>   - errorMessage: Cannot read property 'eval' of null
>         at LessCompiler
> -~- created here: -~-
>     at LessCompiler.Plugin (/Users/vkazakov/dev/Mothership/frontend/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
>     at LessCompiler.CachingWriter [as constructor] (/Users/vkazakov/dev/Mothership/frontend/node_modules/broccoli-caching-writer/index.js:18:10)
>     at new LessCompiler (/Users/vkazakov/dev/Mothership/frontend/node_modules/broccoli-less-single/index.js:19:17)
>     at /Users/vkazakov/dev/Mothership/frontend/node_modules/ember-cli-less/index.js:30:12
>     at Array.map (native)
>     at LESSPlugin.toTree (/Users/vkazakov/dev/Mothership/frontend/node_modules/ember-cli-less/index.js:26:34)
>     at /Users/vkazakov/dev/Mothership/frontend/node_modules/ember-cli-preprocess-registry/preprocessors.js:180:26
>     at Array.forEach (native)
>     at processPlugins (/Users/vkazakov/dev/Mothership/frontend/node_modules/ember-cli-preprocess-registry/preprocessors.js:178:11)
>     at module.exports.preprocessCss (/Users/vkazakov/dev/Mothership/frontend/node_modules/ember-cli-preprocess-registry/preprocessors.js:148:10)
> -~- (end) -~-
>   - errorType: Syntax
>   - location:
>     - column: 0
>     - file: [undefined]
>     - line: 19
>     - treeDir: [undefined]
>   - message: Cannot read property 'eval' of null
>         at LessCompiler
> -~- created here: -~-
>     at LessCompiler.Plugin (/Users/vkazakov/dev/Mothership/frontend/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
>     at LessCompiler.CachingWriter [as constructor] (/Users/vkazakov/dev/Mothership/frontend/node_modules/broccoli-caching-writer/index.js:18:10)
>     at new LessCompiler (/Users/vkazakov/dev/Mothership/frontend/node_modules/broccoli-less-single/index.js:19:17)
>     at /Users/vkazakov/dev/Mothership/frontend/node_modules/ember-cli-less/index.js:30:12
>     at Array.map (native)
>     at LESSPlugin.toTree (/Users/vkazakov/dev/Mothership/frontend/node_modules/ember-cli-less/index.js:26:34)
>     at /Users/vkazakov/dev/Mothership/frontend/node_modules/ember-cli-preprocess-registry/preprocessors.js:180:26
>     at Array.forEach (native)
>     at processPlugins (/Users/vkazakov/dev/Mothership/frontend/node_modules/ember-cli-preprocess-registry/preprocessors.js:178:11)
>     at module.exports.preprocessCss (/Users/vkazakov/dev/Mothership/frontend/node_modules/ember-cli-preprocess-registry/preprocessors.js:148:10)
> -~- (end) -~-
>   - name: BuildError
>   - nodeAnnotation: [undefined]
>   - nodeName: LessCompiler
>   - originalErrorMessage: Cannot read property 'eval' of null
>   - stack: TypeError: Cannot read property 'eval' of null
>     at Array.<anonymous> (/Users/vkazakov/dev/Mothership/frontend/node_modules/less/lib/less/tree/variable.js:39:31)
>     at Node.Variable.find (/Users/vkazakov/dev/Mothership/frontend/node_modules/less/lib/less/tree/variable.js:55:17)
>     at Node.Variable.eval (/Users/vkazakov/dev/Mothership/frontend/node_modules/less/lib/less/tree/variable.js:27:21)
>     at Node.Expression.eval (/Users/vkazakov/dev/Mothership/frontend/node_modules/less/lib/less/tree/expression.js:39:37)
>     at Node.Value.eval (/Users/vkazakov/dev/Mothership/frontend/node_modules/less/lib/less/tree/value.js:23:30)
>     at Node.Declaration.eval (/Users/vkazakov/dev/Mothership/frontend/node_modules/less/lib/less/tree/declaration.js:62:33)
>     at Node.Ruleset.eval (/Users/vkazakov/dev/Mothership/frontend/node_modules/less/lib/less/tree/ruleset.js:181:50)
>     at module.exports (/Users/vkazakov/dev/Mothership/frontend/node_modules/less/lib/less/transform-tree.js:76:22)
>     at ParseTree.toCSS (/Users/vkazakov/dev/Mothership/frontend/node_modules/less/lib/less/parse-tree.js:14:25)
>     at /Users/vkazakov/dev/Mothership/frontend/node_modules/less/lib/less/render.js:35:40

**Comment by knownasilya** [comment]
@jasonmit any thoughts on this?

**Comment by jasonmit** [comment]
@knownasilya haven't had a chance to look, is it still happening?

**Comment by knownasilya** [comment]
https://github.com/gpoitch/ember-cli-less/issues/69 also seems 2.0 specific
